### ISSUE TITLE
metadata entry "sensor_name" does not accept integers in its value

### ISSUE THREAD

**Issue by saveriogzz** [ltelab/disdrodb#4]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When using the entry `Parsivel2` as entry in the metadata's `sensor_name` key, I receive a TypeError and the script stops executing.

### Expected Behavior

It should be ideally possible to use any string as sensor_name's value

### Steps To Reproduce

- Use the [metadata here](https://github.com/ltelab/disdrodb/files/8034891/PAR001.txt)
- Convert them to yml as it is the only format accept at the moment
- See difference in behaviour when using `Parsivel` (ends execution) and `Parsivel2` (error!)

### Anything else?

The full traceback error:

```bash
There are the following metadata files without corresponding data: ['PAR002', '20', 'testconki', 'PAR003']
 - L0 processing of station_id PAR001 has started.
 - 1 files to process in /home/sguzzo/Parsivel/RAW_TELEGRAM
 - Conversion to Apache Parquet started.
 - Conversion to Apache Parquet ended.
Traceback (most recent call last):
  File "/home/sguzzo/PycharmProjects/disdrodb/disdrodb/readers/DELFT/parser_RASPBERRY.py", line 487, in <module>
    main()
  File "/home/sguzzo/miniconda3/envs/disdrodb/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/sguzzo/miniconda3/envs/disdrodb/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/sguzzo/miniconda3/envs/disdrodb/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/sguzzo/miniconda3/envs/disdrodb/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/sguzzo/PycharmProjects/disdrodb/disdrodb/readers/DELFT/parser_RASPBERRY.py", line 407, in main
    check_L0_standards(fpath=fpath,
  File "/home/sguzzo/PycharmProjects/disdrodb/disdrodb/check_standards.py", line 48, in check_L0_standards
    if not df[column].between(*dict_field_value_range[column]).all():
  File "/home/sguzzo/miniconda3/envs/disdrodb/lib/python3.9/site-packages/pandas/core/series.py", line 5110, in between
    lmask = self >= left
  File "/home/sguzzo/miniconda3/envs/disdrodb/lib/python3.9/site-packages/pandas/core/ops/common.py", line 69, in new_method
    return method(self, other)
  File "/home/sguzzo/miniconda3/envs/disdrodb/lib/python3.9/site-packages/pandas/core/arraylike.py", line 52, in __ge__
    return self._cmp_method(other, operator.ge)
  File "/home/sguzzo/miniconda3/envs/disdrodb/lib/python3.9/site-packages/pandas/core/series.py", line 5502, in _cmp_method
    res_values = ops.comparison_op(lvalues, rvalues, op)
  File "/home/sguzzo/miniconda3/envs/disdrodb/lib/python3.9/site-packages/pandas/core/ops/array_ops.py", line 284, in comparison_op
    res_values = comp_method_OBJECT_ARRAY(op, lvalues, rvalues)
  File "/home/sguzzo/miniconda3/envs/disdrodb/lib/python3.9/site-packages/pandas/core/ops/array_ops.py", line 73, in comp_method_OBJECT_ARRAY
    result = libops.scalar_compare(x.ravel(), y, op)
  File "pandas/_libs/ops.pyx", line 107, in pandas._libs.ops.scalar_compare
TypeError: '>=' not supported between instances of 'str' and 'int'

```

### What python version are you using?

3.9.*

**Comment by ghiggi** [comment]
This issue let me realize that we will need to slightly refactor a bit the code to facilitate the processing with custom sensor types/names. I include in the conversation also @KimCandolfi.

`sensor_name `is a very special metadata key that **must** be specified to run the processing. 

Currently, the processing run only if sensor_name is `"Parsivel"` !!!

In order to enable processing with other `sensor_name`  (i.e. "Parsivel2", "LPM", "<ad-hoc_name>), you need to follow these steps: 
1. Add code to [ `standards.py`](https://github.com/ltelab/disdrodb/blob/main/disdrodb/standards.py#L467) functions which enable to retrieve diameter and velocity bins characteristics as well as the raw spectrum size as a function of the `sensor_name`.
If someone is using an OTT Parsivel with custom bin sizes (i.e. in some NASA campaigns if I recall correctly), one could specify a custom `sensor_name` (i.e. `APU`) which enables the retrieval of the correct information later on in the processing.  
2. Add the desired array chunking information to `get_L1_chunks ` function that is currently is located [L1_proc.py](https://github.com/ltelab/disdrodb/blob/main/disdrodb/L1_proc.py#L204). We could think to move this also to `standards.py `to have a unique file where a contributor needs to add all the necessary info.
3. Add relevant infos to `get_field_value_range_dict ` and `get_field_value_options_dict `in [check_standards.py](https://github.com/ltelab/disdrodb/blob/main/disdrodb/check_standards.py#L389). We could think to move also this function to `standards.py`

I also wonder if we should not add an additional metadata to differentiate between the possibly custom `sensor_name `and the actual instrument type. Or rely on `sensor_long_name` and check that it belongs to the expected values.

**Comment by saveriogzz** [comment]
Hey @ghiggi , can we consider this resolved?
